from tkinter import *
window = Tk()
window.geometry("300x300")
window.title("using a listbox")
myLabel = Label(window, text="Provincial capitals of SA")
myLabel.pack()
myListbox1 = Listbox(window)
myListbox1.insert(1, "Cape Town")
myListbox1.insert(2, "Bloemfontein")
myListbox1.insert(3,"Durban")
myListbox1.insert(4, "Pretoria")
myListbox1.insert(5, "Joburg")
myListbox1.insert(6, "Kimberley")
myListbox1.insert(7, "East London")
myListbox1.insert(8, "Polokwane")
myListbox1.insert(9, "Witbank")
myListbox1.pack()
window.mainloop()
